In [3]:
# [https://zhuanlan.zhihu.com/p/548235865]

In [ ]:
import torch

# 维度转换

In [ ]:
# torch.view(shape)：新旧张量数据元素相同，但是尺寸不同

In [2]:

a = torch.randn(4, 4, 2)
print(a.size())     # torch.Size([4, 4, 2])
a = a.view(2, 16)
print(a.size())     # torch.Size([2, 16])
a = a.view(8, -1)
print(a.size())     # torch.Size([8, 4])
a = a.view(8, 3)
print(a.size())     # RuntimeError: shape '[8, 3]' is invalid for input of size 32

torch.Size([4, 4, 2])
torch.Size([2, 16])
torch.Size([8, 4])


RuntimeError: shape '[8, 3]' is invalid for input of size 32

#  维度压缩

In [ ]:
# input (Tensor) – 输入张量
# dim (int, optional) – 如果给定，则只会在给定维度压缩
# out (Tensor, optional) – 输出张量

In [4]:
a = torch.randn(4, 4, 1, 2, 1)
a = torch.squeeze(a)
print(a.size())     # torch.Size([4, 4, 2])

a = torch.randn(4, 4, 1, 2, 1)
a = torch.squeeze(a, dim=2)
print(a.size())     # torch.Size([4, 4, 2, 1])

a = torch.randn(4, 4, 1, 2, 1)
a = torch.squeeze(a, dim=1)
print(a.size())     # torch.Size([4, 4, 1, 2, 1])

a = torch.randn(4, 4, 1, 2, 1)
a = torch.squeeze(a, dim=0)
print(a.size())     # torch.Size([4, 4, 1, 2, 1])

torch.Size([4, 4, 2])
torch.Size([4, 4, 2, 1])
torch.Size([4, 4, 1, 2, 1])


# 维度扩展

In [ ]:
# tensor (Tensor) – 输入张量
# dim (int) – 插入维度的索引
# out (Tensor, optional) – 输出张量

In [5]:
a = torch.randn(4, 4, 2)
print(a.size())     # torch.Size([4, 4, 2])
a = torch.unsqueeze(a, dim=1)
print(a.size())     # torch.Size([4, 1, 4, 2])

torch.Size([4, 4, 2])
torch.Size([4, 1, 4, 2])


# 维度填充

In [ ]:
# pad - 扩充维度，预先定义出某维度上的扩充参数（具体见示例）
# mode - 扩充方法：'constant', 'reflect' 和 'replicate' 三种模式，分别表示常量，反射，复制
# value - 扩充时指定补充值，仅在 mode = 'constant' 时有效

In [7]:
import torch.nn.functional as F

a = torch.zeros(2, 2, 1)
print(a)
# tensor([[[0.],
#          [0.]],
#         [[0.],
#          [0.]]])
print(a.size())
# torch.Size([2, 2, 1])

a = torch.zeros(2, 2, 1)
a = F.pad(a, pad=(1, 2), mode='constant', value=1)  # 在倒数第一个维度上，左边填充 1 个维数，右边填充 2 个维数
print(a)
# tensor([[[1., 0., 1., 1.],
#          [1., 0., 1., 1.]],
#         [[1., 0., 1., 1.],
#          [1., 0., 1., 1.]]])
print(a.size())
# torch.Size([2, 2, 4])

a = torch.zeros(2, 2, 1)
a = F.pad(a, pad=(1, 2, 2, 1), mode='constant', value=1)    # 在倒数第一个维度上，左边填充 1 个维数，右边填充 2 个维数；在倒数第二个维度上，左边填充 2 个维数，右边填充 1 个维数
print(a)
# tensor([[[1., 1., 1., 1.],
#          [1., 1., 1., 1.],
#          [1., 0., 1., 1.],
#          [1., 0., 1., 1.],
#          [1., 1., 1., 1.]],
#         [[1., 1., 1., 1.],
#          [1., 1., 1., 1.],
#          [1., 0., 1., 1.],
#          [1., 0., 1., 1.],
#          [1., 1., 1., 1.]]])
print(a.size())
# torch.Size([2, 5, 4])

a = torch.zeros(2, 2, 1)
a = F.pad(a, pad=(1, 2, 2, 1,1,1), mode='constant', value=1)    # 在倒数第一个维度上，左边填充 1 个维数，右边填充 2 个维数；在倒数第二个维度上，左边填充 2 个维数，右边填充 1 个维数
# 在倒数第一个维度上，左边填充 1 个维数，右边填充 2 个维数；在倒数第二个维度上，左边填充 2 个维数，右边填充 1 个维数;在倒数第二个维度上，左边填充 1 个维数，右边填充 1 个维数
print(a)
# tensor([[[1., 1., 1., 1.],
#          [1., 1., 1., 1.],
#          [1., 1., 1., 1.],
#          [1., 1., 1., 1.],
#          [1., 1., 1., 1.]],
#
#         [[1., 1., 1., 1.],
#          [1., 1., 1., 1.],
#          [1., 0., 1., 1.],
#          [1., 0., 1., 1.],
#          [1., 1., 1., 1.]],
#
#         [[1., 1., 1., 1.],
#          [1., 1., 1., 1.],
#          [1., 0., 1., 1.],
#          [1., 0., 1., 1.],
#          [1., 1., 1., 1.]],
#
#         [[1., 1., 1., 1.],
#          [1., 1., 1., 1.],
#          [1., 1., 1., 1.],
#          [1., 1., 1., 1.],
#          [1., 1., 1., 1.]]])
# torch.Size([4, 5, 4])
print(a.size())
# torch.Size([4, 5, 4])

tensor([[[0.],
         [0.]],

        [[0.],
         [0.]]])
torch.Size([2, 2, 1])
tensor([[[1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.]]])
torch.Size([2, 2, 4])
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 1., 1., 1.]]])
torch.Size([2, 5, 4])
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1