### 环境:dassl

In [3]:
import torch
import clip
from PIL import Image


tensor([[ 0.0545, -0.0062,  0.0496,  ..., -0.6641, -0.1282, -0.4951],
        [ 0.1443,  0.0224, -0.2910,  ..., -0.4468, -0.3425,  0.1804],
        [ 0.1979, -0.2041, -0.1533,  ..., -0.4509, -0.5664,  0.0596]],
       device='cuda:0', dtype=torch.float16)
tensor([[ 3.1348e-01, -1.4526e-01,  3.0347e-01, -1.9958e-01,  1.5244e-02,
         -1.0352e-01,  1.5576e-01,  2.9492e-01,  4.8096e-01, -7.0229e-03,
         -3.1470e-01,  1.2976e-01, -1.3818e-01,  5.4785e-01,  2.1362e-01,
         -3.0396e-01, -1.5698e-01,  5.4199e-01, -4.2236e-01,  1.9373e-01,
          2.2064e-02, -1.2384e-01,  1.5112e-01,  8.3252e-02, -5.9277e-01,
          5.9082e-01, -1.4453e-01,  2.0801e-01,  2.4300e-03, -2.7930e-01,
          2.5586e-01,  2.3816e-01, -1.4941e-01,  7.6318e-01,  2.6978e-01,
          2.8671e-02,  1.5710e-01,  4.3042e-01,  1.0239e-02, -2.1387e+00,
         -6.1707e-02,  3.6768e-01, -2.6050e-01, -3.4180e-01, -1.6992e-01,
         -7.1582e-01, -3.4277e-01, -5.0629e-02, -3.2471e-01, -1.1914e-01,
    

In [4]:

device = "cuda" if torch.cuda.is_available() else "cpu"
model, preprocess = clip.load("ViT-B/32", device=device)


torch.Size([3, 512])
torch.Size([1, 512])
Label probs: [[0.9927   0.004253 0.003016]]


In [8]:
image = preprocess(Image.open("./images/CLIP.png")).unsqueeze(0).to(device)
text = clip.tokenize(["a a diagram", "a dog", "a cat"]).to(device)


In [12]:
image.shape

torch.Size([1, 3, 224, 224])

In [9]:
text

tensor([[49406,   320,   320, 22697, 49407,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0],
        [49406,   320,  1929, 49407,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0, 

In [10]:

with torch.no_grad():
    image_features = model.encode_image(image)
    text_features = model.encode_text(text)
    print(text_features.shape)
    print(image_features.shape)
    logits_per_image, logits_per_text = model(image, text)
    probs = logits_per_image.softmax(dim=-1).cpu().numpy()

print("Label probs:", probs)  # prints: [[0.9927937  0.00421068 0.00299572]]

torch.Size([3, 512])
torch.Size([1, 512])
Label probs: [[0.9917   0.004963 0.003521]]
